import { useState, useRef, useEffect } from "react";
import { Camera, ArrowLeft, RotateCcw, Zap, Target, ScanLine } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import AROverlay from "@/components/ar-overlay";
import { useCamera } from "@/hooks/useCamera";

export default function CameraAR() {
  const [isARActive, setIsARActive] = useState(true);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisResult, setAnalysisResult] = useState<any>(null);
  const [scanMode, setScanMode] = useState<'equipment' | 'diagnostic' | 'safety'>('equipment');
  const videoRef = useRef<HTMLVideoElement>(null);
  const { stream, startCamera, stopCamera, captureImage, error } = useCamera();
  const [cameraInitialized, setCameraInitialized] = useState(false);

  useEffect(() => {
    let mounted = true;
    
    const initCamera = async () => {
      if (!cameraInitialized && mounted) {
        await startCamera();
        setCameraInitialized(true);
      }
    };

    initCamera();

    return () => {
      mounted = false;
      if (cameraInitialized) {
        stopCamera();
        setCameraInitialized(false);
      }
    };
  }, []);

  useEffect(() => {
    if (stream && videoRef.current && !videoRef.current.srcObject) {
      videoRef.current.srcObject = stream;
      videoRef.current.onloadedmetadata = () => {
        videoRef.current?.play().catch(console.error);
      };
    }
  }, [stream]);

  const handleCapture = async () => {
    if (!stream) return;
    
    setIsAnalyzing(true);
    try {
      const imageData = await captureImage();
      if (imageData) {
        // Send image to AI for analysis
        const response = await fetch('/api/analyze-image', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            image: imageData,
            scanMode: scanMode,
            context: `Gas station equipment ${scanMode} scan`
          }),
        });

        if (response.ok) {
          const result = await response.json();
          setAnalysisResult(result);
        } else {
          console.error('Failed to analyze image');
          setAnalysisResult({
            equipmentType: "Analysis Failed",
            model: "Unable to connect to AI service",
            issues: ["Image analysis service unavailable"],
            recommendations: ["Please try again or contact support"],
            safetyNotes: ["Follow standard safety procedures"],
            confidence: 0.0
          });
        }
      }
    } catch (error) {
      console.error("Error capturing image:", error);
      setAnalysisResult({
        equipmentType: "Error",
        model: "Capture Failed",
        issues: ["Unable to capture image"],
        recommendations: ["Check camera permissions and try again"],
        safetyNotes: ["Follow standard safety procedures"],
        confidence: 0.0
      });
    } finally {
      setIsAnalyzing(false);
    }
  };

  // AR labels will be dynamically generated by AI analysis
  const arLabels: any[] = [];

  return (
    <div className="relative h-full bg-black overflow-hidden">
      {/* Header Controls */}
      <div className="absolute top-4 left-4 right-4 z-20 flex justify-between items-center">
        <div className="flex space-x-2">
          <Button
            variant="outline"
            size="sm"
            className="bg-black bg-opacity-50 text-white border-white"
            onClick={() => window.history.back()}
          >
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <Button
            variant="outline"
            size="sm"
            className={`bg-black bg-opacity-50 border-white ${isARActive ? 'text-green-400' : 'text-white'}`}
            onClick={() => setIsARActive(!isARActive)}
          >
            <Target className="h-4 w-4 mr-1" />
            AR {isARActive ? 'ON' : 'OFF'}
          </Button>
        </div>
        
        <div className="flex items-center space-x-2">
          <Badge variant="outline" className="bg-black bg-opacity-50 text-white border-white">
            <ScanLine className="h-3 w-3 mr-1" />
            {scanMode.toUpperCase()}
          </Badge>
        </div>
      </div>

      {/* Camera View */}
      <div className="relative h-full">
        {stream ? (
          <>
            <video
              ref={videoRef}
              autoPlay
              playsInline
              muted
              className="w-full h-full object-cover"
            />
            
            {/* AR Overlay - only show if analysis result has AR data */}
            {isARActive && analysisResult?.arLabels && (
              <AROverlay labels={analysisResult.arLabels} />
            )}
            
            {/* Camera Crosshairs */}
            <div className="absolute inset-0 pointer-events-none">
              <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
                <div className="w-12 h-12 border-2 border-white opacity-50 rounded-full">
                  <div className="w-full h-0.5 bg-white absolute top-1/2 transform -translate-y-1/2"></div>
                  <div className="h-full w-0.5 bg-white absolute left-1/2 transform -translate-x-1/2"></div>
                </div>
              </div>
            </div>

            {/* Scan Overlay Animation */}
            <div className="absolute inset-0 pointer-events-none">
              <div className="absolute inset-4 border-2 border-blue-400 opacity-30 rounded-lg">
                <div className="absolute top-0 left-0 w-8 h-8 border-t-2 border-l-2 border-blue-400"></div>
                <div className="absolute top-0 right-0 w-8 h-8 border-t-2 border-r-2 border-blue-400"></div>
                <div className="absolute bottom-0 left-0 w-8 h-8 border-b-2 border-l-2 border-blue-400"></div>
                <div className="absolute bottom-0 right-0 w-8 h-8 border-b-2 border-r-2 border-blue-400"></div>
              </div>
            </div>
          </>
        ) : (
          <div className="flex items-center justify-center h-full bg-gray-900">
            <div className="text-center text-white p-8">
              <Camera className="h-16 w-16 mx-auto mb-4 opacity-50" />
              <p className="text-lg mb-2">
                {error ? "Camera Error" : "Starting Camera..."}
              </p>
              <p className="text-sm opacity-75 mb-4">
                {error || "Please allow camera access to use AR features"}
              </p>
              {error && (
                <Button 
                  onClick={() => {
                    setCameraInitialized(false);
                    startCamera();
                  }} 
                  variant="outline" 
                  className="text-white border-white"
                >
                  Retry Camera
                </Button>
              )}
            </div>
          </div>
        )}

        {/* Analysis Loading Overlay */}
        {isAnalyzing && (
          <div className="absolute inset-0 bg-black bg-opacity-75 flex items-center justify-center z-10">
            <div className="text-center text-white">
              <div className="relative">
                <div className="animate-spin rounded-full h-16 w-16 border-4 border-white border-t-transparent mx-auto mb-4"></div>
                <Zap className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 h-6 w-6" />
              </div>
              <p className="text-lg">Analyzing Equipment...</p>
              <p className="text-sm opacity-75">Using AI vision to identify components</p>
            </div>
          </div>
        )}

        {/* Analysis Result Overlay */}
        {analysisResult && (
          <div className="absolute top-20 left-4 right-4 bottom-32 z-10">
            <Card className="bg-black bg-opacity-90 text-white border-gray-600 h-full">
              <CardContent className="p-4 h-full overflow-y-auto">
                <div className="flex justify-between items-start mb-3">
                  <h3 className="font-semibold text-lg">AI Analysis Result</h3>
                  <Button 
                    variant="ghost" 
                    size="sm"
                    onClick={() => setAnalysisResult(null)}
                    className="text-white p-1 hover:bg-gray-700"
                  >
                    ×
                  </Button>
                </div>
                
                <div className="space-y-4 text-sm">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-blue-300 font-medium mb-1">Equipment</p>
                      <p className="text-white">{analysisResult.equipmentType}</p>
                    </div>
                    <div>
                      <p className="text-blue-300 font-medium mb-1">Model</p>
                      <p className="text-white">{analysisResult.model}</p>
                    </div>
                  </div>
                  
                  <div>
                    <p className="text-blue-300 font-medium mb-2">Confidence</p>
                    <div className="flex items-center space-x-2">
                      <div className="flex-1 bg-gray-600 rounded-full h-2">
                        <div 
                          className="bg-green-400 h-2 rounded-full transition-all duration-300" 
                          style={{width: `${analysisResult.confidence * 100}%`}}
                        ></div>
                      </div>
                      <span className="text-white font-medium">{Math.round(analysisResult.confidence * 100)}%</span>
                    </div>
                  </div>
                  
                  {analysisResult.issues.length > 0 && (
                    <div>
                      <p className="text-red-300 font-medium mb-2">Issues Found</p>
                      <ul className="space-y-1">
                        {analysisResult.issues.map((issue: string, index: number) => (
                          <li key={index} className="flex items-start space-x-2">
                            <span className="text-red-400 mt-1 text-xs">●</span>
                            <span className="text-white">{issue}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  
                  {analysisResult.recommendations.length > 0 && (
                    <div>
                      <p className="text-green-300 font-medium mb-2">Recommendations</p>
                      <ul className="space-y-1">
                        {analysisResult.recommendations.map((rec: string, index: number) => (
                          <li key={index} className="flex items-start space-x-2">
                            <span className="text-green-400 mt-1 text-xs">✓</span>
                            <span className="text-white">{rec}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  
                  {analysisResult.safetyNotes.length > 0 && (
                    <div className="border-t border-gray-600 pt-3">
                      <p className="text-yellow-300 font-medium mb-2">Safety Notes</p>
                      <ul className="space-y-1">
                        {analysisResult.safetyNotes.map((note: string, index: number) => (
                          <li key={index} className="flex items-start space-x-2">
                            <span className="text-yellow-400 mt-1 text-xs">⚠</span>
                            <span className="text-white">{note}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          </div>
        )}
      </div>

      {/* Bottom Controls */}
      <div className="absolute bottom-6 left-4 right-4 z-20">
        {/* Scan Mode Toggle */}
        <div className="flex justify-center space-x-2 mb-4">
          {[
            { mode: 'equipment', label: 'Equipment', icon: Target },
            { mode: 'diagnostic', label: 'Diagnostic', icon: Zap },
            { mode: 'safety', label: 'Safety', icon: ScanLine }
          ].map(({ mode, label, icon: Icon }) => (
            <Button
              key={mode}
              variant={scanMode === mode ? "default" : "outline"}
              size="sm"
              onClick={() => setScanMode(mode as any)}
              className={scanMode === mode ? '' : 'bg-black bg-opacity-50 text-white border-white'}
            >
              <Icon className="h-4 w-4 mr-1" />
              {label}
            </Button>
          ))}
        </div>

        {/* Capture Controls */}
        <div className="flex justify-center space-x-4">
          <Button
            variant="outline" 
            className="bg-black bg-opacity-50 text-white border-white"
            onClick={() => setIsARActive(!isARActive)}
          >
            <RotateCcw className="h-4 w-4 mr-2" />
            Toggle AR
          </Button>
          
          <Button 
            onClick={handleCapture}
            disabled={isAnalyzing || !stream}
            className="bg-blue-600 hover:bg-blue-700 text-white px-8"
          >
            <Camera className="h-5 w-5 mr-2" />
            {isAnalyzing ? 'Analyzing...' : 'Scan Equipment'}
          </Button>
        </div>
      </div>
    </div>
  );
}